name: "IME júnior"
description: "Site da empresa júnior do IME"

#url: "www.imejunior.com.br"
#url: http://localhost:4000
#baseurl: /yanmartins.github.io
baseurl: /

paginate: 10
paginate_path: "blog/page:num"

markdown: rdiscount
permalink: /blog/:year/:title.html
