name: "IME júnior"
description: "Site da empresa júnior do IME"

#url: "www.imejunior.com.br"

paginate: 5
paginate_path: "blog/page:num"

markdown: rdiscount
permalink: /blog/:year/:title.html

excerpt_separator: "<!--more-->"
